# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  myproject: 'BlazorPeliculas/Server/BlazorPeliculas.Server.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Compilando el proyecto'
- task: CmdLine@2
  displayName: 'Instalando el EF Core CLI'
  inputs:
    script: 'dotnet tool install --global dotnet-ef'
- task: CmdLine@2
  displayName: 'Generando el script de las migraciones'
  inputs:
    script: 'dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\migrate.sql --project $(myproject)'
- task: DotNetCoreCLI@2
  displayName: 'Creando los archivos finales del proyecto'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(myproject)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x86'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publicando los artefactos localmente'
